services:
  php:
    build:
      context: ./php
    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm run build"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: serwisownik
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  db_data:
